name: xhec-mlops-abalone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pip-tools=7.3.0
  - pandas=2.1.1
  - prefect=2.13.7
  - loguru=0.7.2
  - seaborn=0.12.2
  - scikit-learn=1.5.2
  - mlflow=2.7.1
  - pydantic<2
  - pre-commit=3.4.0
  - black=22.12.0
  - isort=5.12.0
  - pep8-naming=0.13.3
  - jupyter  # For black[jupyter] support
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
